### ISSUE TITLE
About evaluation indicators

### ISSUE THREAD

**Issue by M0ck4ry** [mobaidoctor/polyp-ddpm#4]
I'm very sorry to trouble you again. After receiving your reply, I learned about KID, IS, and FID indicators, but unfortunately, I still couldn't evaluate the synthesized and original images. I would like to comment again and hope that you can publish the evaluation codes related to KID, IS, and FID after seeing them. I would greatly appreciate it if you could publish them!

**Comment by mobaidoctor** [comment]
We didn't write any specific code for FID, KID, or IS evaluation; instead, we simply used the torch-fidelity tool (https://github.com/toshas/torch-fidelity) that I mentioned in my response to your previous question. To evaluate, simply generate synthetic images and compare them with real images using the following command:
fidelity --gpu 0 --isc --fid --kid --kid-subset-size [number of images] --input1 [synthetic images directory] --input2 [real images directory]

**Comment by M0ck4ry** [comment]
> We didn't write any specific code for FID, KID, or IS evaluation; instead, we simply used the torch-fidelity tool (https://github.com/toshas/torch-fidelity) that I mentioned in my response to your previous question. To evaluate, simply generate synthetic images and compare them with real images using the following command: fidelity --gpu 0 --isc --fid --kid --kid-subset-size [number of images] --input1 [synthetic images directory] --input2 [real images directory]

Thank you very much for your reply again. I have successfully conducted the evaluation. May your research go smoothly!
